# Generated by Django 4.2.7 on 2024-02-10 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
            ],
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisaRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_visa_required', models.TextField(blank=True, null=True)),
                ('visa_upon_arrival', models.TextField(blank=True, null=True)),
                ('visa_fees_below_100', models.TextField(blank=True, null=True)),
                ('visa_fees_100_200', models.TextField(blank=True, null=True)),
                ('visa_fees_200_400', models.TextField(blank=True, null=True)),
                ('visa_fees_above_400', models.TextField(blank=True, null=True)),
                ('health_requirements', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.visatype')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(max_length=255)),
                ('purpose_of_travel', models.CharField(max_length=100)),
                ('preferred_languages', models.TextField(null=True)),
                ('notification_preferences', models.TextField(null=True)),
                ('client_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('citizenship', models.ManyToManyField(related_name='citizenship', to='accounts.country')),
                ('country_of_residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residence', to='accounts.country')),
                ('travel_destination', models.ManyToManyField(related_name='travel_destination', to='accounts.country')),
                ('travel_history', models.ManyToManyField(blank=True, related_name='travel_history', to='accounts.country')),
                ('travel_plans', models.ManyToManyField(blank=True, related_name='travel_plan', to='accounts.travelplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='travelplan',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attributes', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='country',
            name='visa_requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_visa_requirements', to='accounts.visarequirements'),
        ),
    ]
