# Generated by Django 4.2.7 on 2024-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visatype',
            name='processing_time',
            field=models.CharField(default='2-3 Business Days', max_length=255),
        ),
        migrations.AddField(
            model_name='visatype',
            name='visa_group',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
