# Generated by Django 4.2.7 on 2024-02-10 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_visatype_processing_time_visatype_visa_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visarequirements',
            old_name='visa_fees_100_200',
            new_name='visa_application_eligibility',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='travel_destination',
        ),
        migrations.RemoveField(
            model_name='visarequirements',
            name='visa_fees_200_400',
        ),
        migrations.RemoveField(
            model_name='visarequirements',
            name='visa_fees_above_400',
        ),
        migrations.RemoveField(
            model_name='visarequirements',
            name='visa_fees_below_100',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='initial_travel_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_travel_destination', to='accounts.country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_validity_requirement',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subsequent_travel_destinations',
            field=models.ManyToManyField(blank=True, related_name='subsequent_travel_destinations', to='accounts.country'),
        ),
        migrations.AddField(
            model_name='visatype',
            name='visa_fees',
            field=models.TextField(blank=True, null=True),
        ),
    ]
