# Generated by Django 4.2.7 on 2024-02-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpassport_visatypedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisaapplication',
            name='consultation_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uservisaapplication',
            name='consultation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservisaapplication',
            name='consultation_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uservisaapplication',
            name='consultation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
